package ui.string

import ui.string.Strings.*

fun Strings.en(): String =
    when (this) {
        CommonOkay -> "OK"
        CommonCancel -> "Cancel"
        CommonYes -> "Yes"
        CommonNo -> "No"
        CommonBack -> "Back"
        CommonMore -> "More"
        CommonError -> "Error"
        CommonEdit -> "Edit"
        CommonCheck -> "Check"
        CommonImport -> "Import"
        AlertNeedManualPermissionGrantTitle -> "Permission Required"
        AlertNeedManualPermissionGrantMessage ->
            "The app needs your permission to record audio. Please grant the permission in system settings."
        ErrorReadFileFailedMessage -> "Failed to read file."
        ErrorExportDataFailedMessage -> "Failed to export data."
        ExceptionRenameSessionExisting -> "Session named {0} already exists."
        ExceptionRenameSessionInvalid -> "Invalid session name: {0}"
        ExceptionRenameSessionUnexpected -> "Failed to rename session."
        ToastExportDataSuccess -> "Exported successfully"
        ToastExportDataCancel -> "Export cancelled"
        ToastImportReclistSuccess -> "Imported successfully"
        ToastImportReclistFailure -> "Failed to import"
        MainScreenAllSessions -> "All Sessions"
        MainScreenItemSelecting -> "Selecting {0} items"
        MainScreenNewSession -> "Start New Session"
        MainScreenEmpty -> "No sessions yet."
        MainScreenDeleteItemsTitle -> "Delete Sessions"
        MainScreenDeleteItemsMessage ->
            "Are you sure you want to delete {0} session(s)? The recordings will be completely removed from the device."
        SessionScreenCurrentSentenceLabel -> "Current Recording: "
        SessionScreenNoData -> "No data."
        SessionScreenActionOpenDirectory -> "Open Directory"
        SessionScreenActionExport -> "Export"
        SessionScreenActionRenameSession -> "Rename Session"
        SessionScreenTogglePlaying -> "Toggle Playback"
        CreateSessionReclistScreenTitle -> "Select reclist to record"
        CreateSessionReclistScreenActionImport -> "Import Reclist"
        CreateSessionReclistScreenAllReclists -> "All Reclists"
        CreateSessionReclistScreenEmpty -> "Please import a reclist first."
        CreateSessionReclistScreenContinue -> "Finish"
        CreateSessionReclistScreenFailure -> "Failed to create session."
        CreateSessionReclistScreenDeleteItemsTitle -> "Delete Reclists"
        CreateSessionReclistScreenDeleteItemsMessage -> "Are you sure you want to delete {0} reclist(s)?"
        MenuFile -> "File"
        MenuFileNewSession -> "Start New Session"
        MenuFileImportReclist -> "Import Reclist"
        MenuFileOpenDirectory -> "Open Directory"
        MenuFileBack -> "Back"
        MenuEdit -> "Edit"
        MenuEditRenameSession -> "Rename Session"
        MenuEditEditList -> "Edit List"
        MenuAction -> "Action"
        MenuActionNextSentence -> "Next Sentence"
        MenuActionPreviousSentence -> "Previous Sentence"
        MenuActionToggleRecording -> "Toggle Recording"
    }
