# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release Mac ARM

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: macos-15

    steps:
      - uses: actions/checkout@v3

      - name: Get version
        run: |
          APP_VERSION=$(awk -F'=' '/^app.versionName/ {print $2}' gradle.properties)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          if [ "${{ github.event_name }}" = "push" ]; then
            TAG=${{ env.APP_VERSION }}
            if [ "$TAG" != "$APP_VERSION" ]; then
              echo "Tag $TAG does not match app version $APP_VERSION"
              exit 1
            fi
          fi

      - name: Set Flavor
        run: echo "buildkonfig.flavor=release" >> gradle.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Prepare signing
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          KEYCHAIN_PWD: ${{ secrets.KEYCHAIN_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p $KEYCHAIN_PWD build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $KEYCHAIN_PWD build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security find-identity -v
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PWD build.keychain
          echo "compose.desktop.mac.sign=true" > local.properties
          echo "compose.desktop.mac.signing.identity=${{ secrets.MACOS_CERTIFICATE_IDENTITY }}" >> local.properties
          echo "compose.desktop.mac.notarization.appleID=${{ secrets.APPLE_ID }}" >> local.properties
          echo "compose.desktop.mac.notarization.password=${{ secrets.MACOS_APP_PWD }}" >> local.properties
          echo "compose.desktop.mac.notarization.teamID=${{ secrets.APPLE_TEAM_ID }}" >> local.properties
          cat local.properties

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: notarizeDmg

      - name: Rename
        run: |
          VERSION=${{ env.APP_VERSION }}
          echo $VERSION
          mv ./desktopApp/build/compose/binaries/main/dmg/RecStar-1.0.0.dmg ./recstar-$VERSION-mac-arm64.dmg

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: recstar-${{ env.APP_VERSION }}-mac-arm64.dmg
